eureka:
  client:
    # 注册服务中心
    service-url:
      defaultZone: http://47.105.218.58:8763/eureka/,http://47.105.218.58:8761/eureka/,http://47.105.218.58:8762/eureka/
  # 注册中心查看注册服务跳转链接地址：localhost => clientName
#  instance:
#    hostname: product

spring:
  application:
    name: product
  profiles:
    active: hikari
server:
  port: 8080
logging:
  level:
    com.cloud.product.mapper: debug
