eureka:
  client:
    service-url:
      defaultZone: http://47.105.218.58:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xwzq/myconfig.git
          username: 158262751
          password: 158262751sb.
          basedir: D://config/
  rabbitmq:
    host: 47.105.218.58
    port: 5672
    username: guest
    password: guest
  # /{name}-{profiles}.yml
  # /{label}/{name}-{profiles}.yml
  # http://localhost:port/order-a.yml 访问， 根据配置的 git 仓库进行访问
  # name 服务名
  # profiles 环境
  # label 分支(branch)  默认为 master 分支
management:
  endpoints:
    web:
      #      base-path: / #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"  #打开全部请求端点
  #        include: refresh,health,info #打开部分
  # 必须加上端口，不然 404
  server:
    port: 7777
server:
  port: 7777