server:
  port: 7777
eureka:
  client:
    service-url:
      defaultZone: http://47.105.218.58:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xwzq/myconfig.git
          username: 158262751
          password: 158262751sb.
          basedir: /root/config/
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 47.105.218.58
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 7777